### ISSUE TITLE
Support for 13.xx

### ISSUE THREAD

**Issue by genxstylez** [theozaurus/mod_eventful#2]
Hi,

Any plans to update to support the new 13.xx versions of ejabberd?

If not, can you point out which bit of the ejabberd code I should look into in order to make it compatible? 

Cheers!

**Comment by theozaurus** [comment]
Hi,
I no longer use ejabberd so there are no plans to support any other versions. It's been a very long time since I looked at this stuff, you may have some luck asking on the ejabberd dev mailing list.

Good luck!

Theo
