### ISSUE TITLE
Weird issue

### ISSUE THREAD

**Issue by kuno** [theozaurus/mod_eventful#3]
Hi:

Thank for you efforts in this project.

Our company are using a modification of this module alone with ejabberd in one of our company's project. Use `message_hook`  event to send xmpp messages to a http api.

Recently, we found a weird issue,  this module is working well in our local development environment, but in the real production server, if the ejabberd server has many vhosts listing. Only, the last one in the list has `mod_eventful` working for it.

For example, if the `ejabberd.cfg` looks like this

``` erlang
...
{hosts, ["example.net", "example.com", "example.org"]}.
...
```

In the above case, only the `example.org`'s message will be send.

Our ejabberd version is the erlang solution's fork of origin version, you can found their repo at [here](https://github.com/esl/MongooseIM).

And both our development and production server is ubuntu 13.04, local is in a vagrant box, production is hosting on linode.

I knew it's very hard for you to figure our the actual problem, but you might be able to point us to the right direction.

Cheers

**Comment by theozaurus** [comment]
You'll have to try and get your dev environment closer to production environment and dive in with debugging.

I wrote up some notes when I first wrote this module because it was very exploratory. I'll email them to you now.

Let me know if it helps!
