### ISSUE TITLE
Online hook is being called on presence hook

### ISSUE THREAD

**Issue by tudip-technologies** [theozaurus/mod_eventful#4]
Hi,

First, thanks for this great plugin.

I have noticed an issue recently with ejabberd 2.1 though. 
Even when presence packets are sent, the online hook is invoked and that affects overall scalability of ejabberd.

Do you have any idea why that might be happening?

Appreciate all your help!

**Comment by theozaurus** [comment]
I've not used this module in a long time. I can send you some notes I made while making it if you'd like to try and take it further.

**Comment by tudip-technologies** [comment]
Sure, that would definitely help. :)
