### ISSUE TITLE
src/web/mod_eventful.erl:139

### ISSUE THREAD

**Issue by jrvaja** [theozaurus/mod_eventful#5]
Hi There,

I have created a superb module for ejabberd.
I am facing small issue ,however I have used your module many times.
In my project, mod_eventful is not working.
I got error when I compile ./build.sh
src/web/mod_eventful.erl:139: Warning: call to http:request/4 will fail, since it was removed in R15B; use httpc:request/4

I will highly appreciate if you can guide me in this case.

Thanks,

**Comment by theozaurus** [comment]
This looks like you are using a more recent version of Erlang than this code supports. I'm no longer supporting this module. If you dig into the http docs and the code then you maybe able to tweak it to work with R15.
