### ISSUE TITLE
./build.sh Issue :

### ISSUE THREAD

**Issue by jrvaja** [theozaurus/mod_eventful#6]
/usr/lib/ejabberd/mod_eventful# ./build.sh
{"init terminating in do_boot",{undef,[{make,all,[],[]},{init,start_it,1,[]},{init,start_em,1,[]}]}}

Crash dump was written to: erl_crash.dump
init terminating in do_boot ()

**Comment by theozaurus** [comment]
What version of ejabberd are you using?
