### ISSUE TITLE
ejabberd mod_eventful module not working in Ubuntu 14.04 LTS

### ISSUE THREAD

**Issue by gaurangpanchani** [theozaurus/mod_eventful#9]
When in mobile side, invoke ejabberd call then our API not calling and that crash report is listed below.
-------------------------------------------------------------------
Our System	 : Ubuntu 14.04 LTS
ejabberd version : 2.1.1
-------------------------------------------------------------------

Error log path :
var/www/ejabbered/ejabberd.log and found that..

{'module could not be loaded',
[{http,request,
[post,
{"http://192.168.1.60/messages",
[{"Authorization",
"Basic SFRUUCBCQVNJQyBVU0VSTkFNRTpIVFRQIEJBU0lDIFBBU1NXT1JE"}],
"application/x-www-form-urlencoded",
"from=ABCUSER%40192.168.1.60/15310114851488363705601144&to=XYZUSER%40192.168.1.60&type=chat&subject=&body=%7B%22isdownload%22:false%2C%22issent%22:false%2C%22fromuserid%22:%22ABCUSER%40192.168.1.60%22%2C%22ptopid%22:%22%22%2C%22messageid%22:%221488363577548%22%2C%22message_time%22:%221488363577911%22%2C%22mediathumb%22:%22%22%2C%22is_read%22:false%2C%22isseen%22:false%2C%22fromprofilepic%22:%22%22%2C%22isread%22:false%2C%22messagesource%22:%22VGhlIG9ubHkgcHJvYmxlbSBJIGhhZCB3YXM%3D%22%2C%22messagetype%22:%22text%22%2C%22fromusername%22:%22ABCUSER%20AB%22%7D&thread="},
[],
[{sync,false},{stream,self}]],
[]},
{mod_eventful,handle_call,3,
[{file,"src/web/mod_eventful.erl"},{line,188}]},
{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,585}]},
{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,239}]}]}

This log may help to get more into it.

**Comment by theozaurus** [comment]
Hi,
This project is deprecated. I can no longer offer any support on it.
Thanks,
Theo

**Comment by gaurangpanchani** [comment]
Thanks for message

**Comment by gaurangpanchani** [comment]
So what should i will use instead of mod_eventful module ?
Any idea or any reference whom i can ask this question ?

Your idea would be highly appriciated

**Comment by theozaurus** [comment]
I would contact [Process One](https://www.process-one.net/en/ejabberd/) who write ejabberd and offer commercial support.
